version: "3.8"

services:
  neo4j:
    image: neo4j:5 # Use a specific version, e.g., 5
    container_name: neo4j_flowlib
    ports:
      - "7474:7474" # HTTP Browser
      - "7687:7687" # Bolt Driver
    volumes:
      - neo4j_data:/data
    environment:
      # Set initial password. CHANGE THIS in production!
      NEO4J_AUTH: neo4j/pleaseChangeThisPassword
      # Required for Neo4j 5+
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      # Optional: Adjust memory settings if needed
      # NEO4J_server_memory_heap_initial__size: 512m
      # NEO4J_server_memory_heap_max__size: 2G
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--spider", "--tries=1", "http://localhost:7474"]
      interval: 5s
      timeout: 1s
      retries: 10

volumes:
  neo4j_data:
    driver: local 