"""Models for execution reflection."""

from typing import Literal, Optional

from pydantic import Field

from flowlib.resources.models.base import StrictBaseModel

# LLM-facing models


class LLMReflectionResult(StrictBaseModel):
    """Reflection result generated by LLM (semantic only)."""

    execution_successful: bool = Field(
        ...,
        description="Whether the execution steps achieved their intended goals"
    )
    issues_found: list[str] = Field(
        default_factory=list,
        description="List of issues or problems identified in execution results"
    )
    reasoning: str = Field(
        ...,
        description="Analysis of what worked and what didn't work"
    )
    next_action: Literal["continue", "replan", "clarify"] = Field(
        ...,
        description="What should happen next: continue (execution successful), replan (need different approach), clarify (need user input)"
    )
    replanning_guidance: Optional[str] = Field(
        default=None,
        description="If next_action is 'replan', what should be done differently"
    )
    clarification_question: Optional[str] = Field(
        default=None,
        description="If next_action is 'clarify', what to ask the user"
    )


# Full models


class ReflectionResult(StrictBaseModel):
    """Complete reflection result with metadata."""

    execution_successful: bool
    issues_found: list[str]
    reasoning: str
    next_action: Literal["continue", "replan", "clarify"]
    replanning_guidance: Optional[str] = None
    clarification_question: Optional[str] = None

    # Programmatic fields
    reflection_time_ms: float = Field(default=0.0, description="Time taken to reflect")
    llm_calls_made: int = Field(default=1, description="Number of LLM calls")


class ReflectionInput(StrictBaseModel):
    """Input for execution reflection."""

    original_goal: str = Field(..., description="The original user request")
    plan_steps: list[dict] = Field(..., description="The planned steps")
    execution_results: list[dict] = Field(..., description="Results from each executed step")
    partial_completion: bool = Field(..., description="Whether some steps succeeded but not all")


class ReflectionOutput(StrictBaseModel):
    """Output from execution reflection."""

    result: ReflectionResult = Field(..., description="The reflection result")
    success: bool = Field(..., description="Whether reflection succeeded")
    processing_time_ms: float = Field(default=0.0, description="Time taken to reflect")
