"""Conversation tool implementation."""


from ....core.todo import TodoItem
from ...decorators import tool
from ...models import (
    PresentationMode,
    ToolExecutionContext,
    ToolPresentationInterface,
    ToolPresentationPreference,
    ToolResult,
    ToolStatus,
)
from .models import ConversationParameters, ConversationResult


@tool(
    parameter_type=ConversationParameters,
    name="conversation",
    tool_category="generic",
    description="Handle conversational interactions and generate responses",
)
class ConversationTool(ToolPresentationInterface):
    """Tool for handling conversational interactions.

    This tool delivers pre-formatted conversational responses from the planner.
    The planner generates the message content, and this tool presents it to the user.

    Required parameters:
    - message: The exact text to present to the user

    Output is used directly without additional presentation layer processing.
    """

    def get_name(self) -> str:
        """Get tool name."""
        return "conversation"

    def get_description(self) -> str:
        """Get tool description."""
        return "Handle conversational interactions and generate responses"

    def get_presentation_preference(self) -> ToolPresentationPreference:
        """Declare that conversation tool output should be used directly.

        Conversation tools generate user-friendly responses that don't need
        additional LLM processing for presentation.

        Returns:
            ToolPresentationPreference with DIRECT mode
        """
        return ToolPresentationPreference(
            mode=PresentationMode.DIRECT,
            reason="Conversation tool generates user-friendly responses that should be presented directly without additional LLM processing",
        )

    async def execute(
        self, todo: TodoItem, params: ConversationParameters, context: ToolExecutionContext
    ) -> ToolResult:
        """Execute conversation interaction - deliver message from planner.

        Args:
            todo: TodoItem describing the conversation task
            params: Validated ConversationParameters instance (generated by engine)
            context: Tool execution context

        Returns:
            ToolResult with conversation response
        """
        try:
            # Simple message delivery - no additional LLM processing
            # The planner already decided what to say
            return ConversationResult(
                status=ToolStatus.SUCCESS, message="Message delivered", response=params.message
            )

        except Exception as e:
            return ConversationResult(
                status=ToolStatus.ERROR, message=f"Failed to deliver message: {str(e)}"
            )
