"""
Pydantic models for messages used in the remote agent execution architecture.
"""

from pydantic import Field, ConfigDict
from flowlib.core.models import StrictBaseModel
from typing import Optional, Dict, Any

class AgentTaskMessage(StrictBaseModel):
    """Message published to the task queue to initiate an agent run."""
    model_config = ConfigDict(frozen=True, extra="allow")
    
    task_id: str = Field(..., description="Unique identifier for this specific task execution.")
    task_description: str = Field(..., description="The high-level goal or instruction for the agent.")
    initial_state_id: Optional[str] = Field(None, description="ID of a previously saved state to resume from. If None, a new state is created.")
    initial_state_data: Optional[Dict[str, Any]] = Field(None, description="Data to initialize a new agent state if initial_state_id is None.")
    agent_config: Optional[Dict[str, Any]] = Field(None, description="Specific configuration overrides for the agent instance for this task.")
    reply_to_queue: Optional[str] = Field(None, description="Optional queue name where the result message should be sent.")
    correlation_id: Optional[str] = Field(None, description="Optional ID to correlate requests and responses.")


class AgentResultMessage(StrictBaseModel):
    """Message published to the results queue upon completion or failure of an agent task."""
    model_config = ConfigDict(frozen=True, extra="allow")
    
    task_id: str = Field(..., description="Unique identifier for the task this result corresponds to.")
    status: str = Field(..., description="Indicates the outcome (e.g., 'SUCCESS', 'FAILURE').")
    final_state_id: Optional[str] = Field(None, description="ID of the agent's final state after execution.")
    result_data: Optional[Dict[str, Any]] = Field(None, description="Output data generated by the agent/flow if successful.")
    error_message: Optional[str] = Field(None, description="Details of the error if the task failed.")
    correlation_id: Optional[str] = Field(None, description="ID to correlate requests and responses, copied from the task message if provided.") 